"use client";

import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

import { UserContext } from "../lib/context";
import EmployeContext, {
  EmployeeContextProvider,
} from "../lib/employeeContext";
import { useUserData } from "../lib/hooks";
import TransactionContext, {
  TransactionContextProvider,
} from "../lib/transactionContext";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const userData = useUserData();
  const employee = [];

  return (
    <html lang="en">
      <body>
        <main>
          <UserContext.Provider
            value={{ user: userData.user, company: userData.company }}
          >
            <main>
              <TransactionContextProvider value={[]}>
                <main>
                  <EmployeeContextProvider value={employee}>
                    <main className={poppins.className}>{children}</main>
                  </EmployeeContextProvider>
                </main>
              </TransactionContextProvider>
            </main>
          </UserContext.Provider>
        </main>
      </body>
    </html>
  );
}
